replicaCount: 2

image:
  repository: myapp
  tag: "1.0"
  pullPolicy: Never

service:
  type: NodePort
  port: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
